"""empty message

Revision ID: 39e1979921aa
Revises: d5a6f174b909
Create Date: 2022-08-13 05:17:49.609291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e1979921aa'
down_revision = 'd5a6f174b909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('search_description', sa.String(length=500), nullable=True))
    op.drop_column('artist', 'description')
    op.add_column('venue', sa.Column('search_description', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'search_description')
    op.add_column('artist', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artist', 'search_description')
    # ### end Alembic commands ###
