"""empty message

Revision ID: d5a6f174b909
Revises: f29a76c451e0
Create Date: 2022-08-12 09:12:50.954355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a6f174b909'
down_revision = 'f29a76c451e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('searching_venues', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('searching_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'description')
    op.drop_column('venue', 'searching_talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('artist', 'description')
    op.drop_column('artist', 'searching_venues')
    op.drop_column('artist', 'website_link')
    op.drop_table('show')
    # ### end Alembic commands ###
